services:
  php-fpm:
    build:
      context: .
      args:
        APP_ENV: dev
    volumes:
      - .:/var/www/html
      - ./php-dev.ini:/usr/local/etc/php/conf.d/php.ini
    environment:
      DATABASE_URL: mysql://root:root@mysql:3307/agrimarket
    ports:
      - "9000:9000"

  nginx:
    image: nginx:alpine
    volumes:
      - .:/var/www/html
      - ./nginx/dev.conf:/etc/nginx/nginx.conf
    ports:
      - "8081:80"
    depends_on:
      - php-fpm

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agrimarket
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  mysql_data: