name: Agrimarket CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'agrimarket/**'

  pull_request:
    branches:
      - main
    paths:
      - 'agrimarket/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: ./agrimarket
          push: true
          tags: ghcr.io/${{ github.repository }}/agrimarket:${{ github.sha }}
          build-args: |
            CI_COMMIT_SHA=${{ github.sha }}

  unit-test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Docker image
        run: docker pull ghcr.io/${{ github.repository }}/agrimarket:${{ github.sha }}

      - name: Run unit tests
        run: |
          docker run --rm ghcr.io/${{ github.repository }}/agrimarket:${{ github.sha }} sh -c "cd agrimarket && composer install --prefer-dist --no-progress --no-interaction"
          docker run --rm ghcr.io/${{ github.repository }}/agrimarket:${{ github.sha }} sh -c "cd agrimarket && ./vendor/bin/phpunit" 

  integration-test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Docker image
        run: docker pull ghcr.io/${{ github.repository }}/agrimarket:${{ github.sha }}

      - name: Run integration tests
        run: |
          docker run --rm ghcr.io/${{ github.repository }}/agrimarket:${{ github.sha }} sh -c "cd agrimarket && composer install --prefer-dist --no-progress --no-interaction"
          docker run --rm ghcr.io/${{ github.repository }}/agrimarket:${{ github.sha }} sh -c "cd agrimarket && ./vendor/bin/phpunit --testsuite=Integration" 

  deploy:
    runs-on: ubuntu-latest
    needs: [unit-test, integration-test]
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Docker image
        run: docker pull ghcr.io/${{ github.repository }}/agrimarket:${{ github.sha }}

      - name: Deploy to staging
        run: |
          docker stop agrimarket-staging || true
          docker rm agrimarket-staging || true
          docker run -d --name agrimarket-staging -p 8080:80 ghcr.io/${{ github.repository }}/agrimarket:${{ github.sha }}

  cleanup:
    runs-on: ubuntu-latest
    needs: deploy
    if: always()
    steps:
      - name: Clean up Docker images and containers
        run: |
          docker image prune -af
          docker container prune -af